# Generated by Django 5.2.16 on 2026-08-10 02:44

import apps.customers.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('approval_pending', 'Approval Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('done', 'Completed'), ('partial', 'Partially Processed'), ('failed', 'Failed')], default='approval_pending', max_length=20)),
                ('salutation', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('identity_type_name', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport')], default='National ID', max_length=20)),
                ('identity_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('working_status', models.CharField(choices=[('Employee', 'Employee'), ('Self Employed', 'Self Employed'), ('Unemployed', 'Unemployed')], default='Employee', max_length=20)),
                ('country', models.CharField(default='KE', max_length=5)),
                ('borrower_type', models.CharField(default='Checkoff', max_length=20)),
                ('lms_customer_id', models.CharField(blank=True, max_length=100)),
                ('lms_loan_disk_id', models.CharField(blank=True, max_length=100)),
                ('registration_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_customer_registrations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_registrations', to='organizations.checkofforganizationmirror')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Registration',
                'verbose_name_plural': 'Customer Registrations',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(choices=[('national_id_front', 'National ID — Front'), ('national_id_back', 'National ID — Back'), ('passport', 'Passport'), ('selfie', 'Selfie')], max_length=20)),
                ('file', models.FileField(upload_to=apps.customers.models.kyc_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('approval_pending', 'Approval Pending'), ('approved', 'Approved'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='approval_pending', max_length=20)),
                ('lms_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='customers.customerregistration')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'ordering': ('document_type',),
            },
        ),
        migrations.AddIndex(
            model_name='customerregistration',
            index=models.Index(fields=['organization', 'status'], name='customers_c_organiz_ba4975_idx'),
        ),
        migrations.AddIndex(
            model_name='customerregistration',
            index=models.Index(fields=['phone_number'], name='customers_c_phone_n_ad32c0_idx'),
        ),
        migrations.AddIndex(
            model_name='customerregistration',
            index=models.Index(fields=['identity_number'], name='customers_c_identit_f64803_idx'),
        ),
        migrations.AddConstraint(
            model_name='kycdocument',
            constraint=models.UniqueConstraint(fields=('registration', 'document_type'), name='unique_document_type_per_registration'),
        ),
    ]
