# Generated by Django 5.2.16 on 2026-08-10 12:26

from django.db import migrations, models


def approved_to_active(apps, schema_editor):
    CustomerRegistration = apps.get_model('customers', 'CustomerRegistration')
    CustomerRegistration.objects.filter(status='approved').update(status='active')


def active_to_approved(apps, schema_editor):
    CustomerRegistration = apps.get_model('customers', 'CustomerRegistration')
    CustomerRegistration.objects.filter(status='active').update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistration',
            name='status',
            field=models.CharField(choices=[('approval_pending', 'Approval Pending'), ('active', 'Active'), ('processing', 'Processing'), ('done', 'Completed'), ('partial', 'Partially Processed'), ('failed', 'Failed')], default='approval_pending', max_length=20),
        ),
        migrations.RunPython(approved_to_active, active_to_approved),
    ]
