# Generated by Django 6.0.1 on 2026-06-26 08:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('payroll', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('success', 'Success'), ('failed', 'Failed')], default='claimed', max_length=20)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='organizations.checkofforganizationmirror')),
            ],
            options={
                'verbose_name': 'Idempotency Key',
                'verbose_name_plural': 'Idempotency Keys',
            },
        ),
        migrations.CreateModel(
            name='RepaymentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('dispatching', 'Dispatching'), ('complete', 'Complete'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_deductions', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('successful_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('successful_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_batches', to='organizations.checkofforganizationmirror')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_batch', to='payroll.payrollupload')),
            ],
            options={
                'verbose_name': 'Repayment Batch',
                'verbose_name_plural': 'Repayment Batches',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='RepaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_sent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual amount sent (capped at loan balance).', max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('lms_response_code', models.CharField(blank=True, max_length=20)),
                ('lms_response_body', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('dispatched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='repayments.repaymentbatch')),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_records', to='payroll.salarydeduction')),
                ('idempotency_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repayments.idempotencykey')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_records', to='organizations.checkofforganizationmirror')),
            ],
            options={
                'verbose_name': 'Repayment Record',
                'verbose_name_plural': 'Repayment Records',
                'ordering': ('-dispatched_at',),
            },
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['organization', 'status'], name='repayments__organiz_a9eded_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencykey',
            index=models.Index(fields=['expires_at'], name='repayments__expires_e516ca_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentbatch',
            index=models.Index(fields=['organization', 'status'], name='repayments__organiz_d0c070_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentbatch',
            index=models.Index(fields=['status', 'date_created'], name='repayments__status_90dcb5_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentrecord',
            index=models.Index(fields=['organization', 'status'], name='repayments__organiz_7c9ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentrecord',
            index=models.Index(fields=['phone_number', 'dispatched_at'], name='repayments__phone_n_55ebdc_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentrecord',
            index=models.Index(fields=['batch', 'status'], name='repayments__batch_i_c1c60c_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentrecord',
            index=models.Index(fields=['deduction'], name='repayments__deducti_b1e964_idx'),
        ),
    ]
