# Generated by Django 5.2.6 on 2026-08-03 13:13

import apps.loans.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequestUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to=apps.loans.models.loan_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('approval_pending', 'Approval Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('done', 'Completed'), ('partial', 'Partially Processed'), ('failed', 'Failed')], default='approval_pending', max_length=20)),
                ('loan_period', models.DateField(help_text='Loan period / month this upload covers (YYYY-MM-01).')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('eligible_rows', models.PositiveIntegerField(default=0)),
                ('ineligible_rows', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loan_uploads', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_request_uploads', to='organizations.checkofforganizationmirror')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_request_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Request Upload',
                'verbose_name_plural': 'Loan Request Uploads',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='LoanRequestBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('dispatching', 'Dispatching'), ('complete', 'Complete'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('ineligible_count', models.PositiveIntegerField(default=0)),
                ('successful_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('successful_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loan_batches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_request_batches', to='organizations.checkofforganizationmirror')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_request_batch', to='loans.loanrequestupload')),
            ],
            options={
                'verbose_name': 'Loan Request Batch',
                'verbose_name_plural': 'Loan Request Batches',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=200)),
                ('employee_id', models.CharField(blank=True, max_length=100)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('loan_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Customer loan_limit from LMS at time of eligibility check.', max_digits=14, null=True)),
                ('existing_loan_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Customer total active loan balance from LMS.', max_digits=14, null=True)),
                ('accessible_loan_limit', models.DecimalField(blank=True, decimal_places=2, help_text='accessible_loan_limit = loan_limit - existing_balance.', max_digits=14, null=True)),
                ('ineligibility_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('eligibility_checking', 'Checking Eligibility'), ('eligible', 'Eligible'), ('ineligible', 'Ineligible'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=30)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lms_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('lms_loan_id', models.CharField(blank=True, help_text='LoanDisk loan_id returned on successful disbursement.', max_length=100)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to='organizations.checkofforganizationmirror')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='loans.loanrequestupload')),
            ],
            options={
                'verbose_name': 'Loan Request',
                'verbose_name_plural': 'Loan Requests',
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddIndex(
            model_name='loanrequestupload',
            index=models.Index(fields=['organization', 'status'], name='loans_loanr_organiz_3a90be_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequestupload',
            index=models.Index(fields=['organization', 'loan_period'], name='loans_loanr_organiz_21d5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequestbatch',
            index=models.Index(fields=['organization', 'status'], name='loans_loanr_organiz_6483a9_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequestbatch',
            index=models.Index(fields=['status', 'date_created'], name='loans_loanr_status_b50ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['organization', 'status'], name='loans_loanr_organiz_de7be3_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['phone_number', 'upload'], name='loans_loanr_phone_n_581f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['idempotency_key'], name='loans_loanr_idempot_7b63ec_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrequest',
            index=models.Index(fields=['upload', 'status'], name='loans_loanr_upload__3d0219_idx'),
        ),
    ]
