# Generated by Django 5.2.6 on 2026-09-14 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_existing_guarantors(apps, schema_editor):
    """Carry forward the old single guarantor_id_number/phone_number
    columns as the first (order=1) LoanGuarantor row for each request."""
    LoanRequest = apps.get_model('loans', 'LoanRequest')
    LoanGuarantor = apps.get_model('loans', 'LoanGuarantor')

    requests = LoanRequest.objects.exclude(guarantor_id_number='')
    guarantors = [
        LoanGuarantor(
            loan_request=req,
            id_number=req.guarantor_id_number,
            phone_number=req.guarantor_phone_number,
            order=1,
        )
        for req in requests
    ]
    LoanGuarantor.objects.bulk_create(guarantors)


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanrequest_guarantor_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Position from the upload (guarantor_1, guarantor_2, ...).')),
            ],
            options={
                'verbose_name': 'Loan Guarantor',
                'verbose_name_plural': 'Loan Guarantors',
                'ordering': ('loan_request', 'order'),
            },
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='loan_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loanrequest'),
        ),
        migrations.RunPython(migrate_existing_guarantors, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='loanrequest',
            name='loans_loanr_guarant_0faa31_idx',
        ),
        migrations.RemoveIndex(
            model_name='loanrequest',
            name='loans_loanr_guarant_1eac14_idx',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='guarantor_id_number',
        ),
        migrations.RemoveField(
            model_name='loanrequest',
            name='guarantor_phone_number',
        ),
        migrations.AddIndex(
            model_name='loanguarantor',
            index=models.Index(fields=['id_number'], name='loans_loang_id_numb_96ddc2_idx'),
        ),
        migrations.AddIndex(
            model_name='loanguarantor',
            index=models.Index(fields=['phone_number'], name='loans_loang_phone_n_095bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='loanguarantor',
            index=models.Index(fields=['loan_request'], name='loans_loang_loan_re_b6df1d_idx'),
        ),
    ]
