# Generated by Django 5.2.6 on 2026-09-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_guarantor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='product',
            field=models.CharField(choices=[('cash', 'Cash'), ('pata_gadget', 'Pata Gadget'), ('shiba_na_dime', 'Shiba na Dime')], default='cash', max_length=20),
        ),
    ]
