# Generated by Django 5.2.16 on 2026-09-15 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='advertisements/')),
                ('starts_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=180)),
                ('price_label', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('starts_at', '-date_created'),
            },
        ),
    ]
