# Generated by Django 6.0.1 on 2026-06-24 07:56

import apps.payroll.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=200)),
                ('employee_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('deduction_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lms_response', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Salary Deduction',
                'verbose_name_plural': 'Salary Deductions',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='PayrollUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=apps.payroll.models.payroll_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('approval_pending', 'Approval Pending'), ('approved', 'Approved'), ('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Processed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('payroll_period', models.DateField(help_text='Payroll period this upload covers (YYYY-MM-01).')),
                ('notes', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_uploads', to='organizations.checkofforganizationmirror')),
            ],
            options={
                'verbose_name': 'Payroll Upload',
                'verbose_name_plural': 'Payroll Uploads',
                'ordering': ('-date_created',),
            },
        ),
    ]
