# Generated by Django 6.0.1 on 2026-06-24 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollupload',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarydeduction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='organizations.checkofforganizationmirror'),
        ),
        migrations.AddField(
            model_name='salarydeduction',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payrollupload'),
        ),
        migrations.AddIndex(
            model_name='payrollupload',
            index=models.Index(fields=['organization', 'status'], name='payroll_pay_organiz_a95dea_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollupload',
            index=models.Index(fields=['organization', 'payroll_period'], name='payroll_pay_organiz_d3960e_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydeduction',
            index=models.Index(fields=['organization', 'status'], name='payroll_sal_organiz_91effb_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydeduction',
            index=models.Index(fields=['phone_number', 'deduction_date'], name='payroll_sal_phone_n_d4b7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydeduction',
            index=models.Index(fields=['idempotency_key'], name='payroll_sal_idempot_16d03a_idx'),
        ),
        migrations.AddIndex(
            model_name='salarydeduction',
            index=models.Index(fields=['upload', 'status'], name='payroll_sal_upload__42a5c4_idx'),
        ),
    ]
