# Generated by Django 6.0.1 on 2026-06-24 07:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('upload', 'Payroll Upload'), ('deduction_create', 'Deduction Created'), ('batch_submit', 'Repayment Batch Submitted'), ('batch_approve', 'Repayment Batch Approved'), ('repayment_sent', 'Repayment Sent to LMS'), ('repayment_failed', 'Repayment Failed'), ('user_create', 'HR User Created'), ('user_deactivate', 'HR User Deactivated')], max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='CheckoffOrganizationMirror',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lms_id', models.CharField(help_text='UUID of this org in the Dime LMS.', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Checkoff Organization',
                'verbose_name_plural': 'Checkoff Organizations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HRUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('admin', 'HR Admin'), ('officer', 'Payroll Officer'), ('viewer', 'Read-Only Viewer')], default='officer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'HR User',
                'verbose_name_plural': 'HR Users',
                'ordering': ('user__email',),
            },
        ),
    ]
