# Generated by Django 6.0.1 on 2026-07-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('upload', 'Payroll Upload'), ('upload_delete', 'Payroll Upload Deleted'), ('deduction_create', 'Deduction Created'), ('batch_submit', 'Repayment Batch Submitted'), ('batch_approve', 'Repayment Batch Approved'), ('repayment_sent', 'Repayment Sent to LMS'), ('repayment_failed', 'Repayment Failed'), ('user_create', 'HR User Created'), ('user_deactivate', 'HR User Deactivated')], max_length=50),
        ),
    ]
